Namespace(batchSize=16, cuda=True, dataset='datasets/', lr=0.0001, momentum=0.9, nEpochs=2500, resume='', start_epoch=1, step=1000, test_path='dataset/test/', threads=16, validate_path='datasets/validate/', weight_decay=0)
===> Loading datasets
===> Building model
n_pyramids: 1 n_pyramid_cells: (3, 2, 1, 1, 1, 1)
===> Setting GPU
===> Setting Optimizer
===> Training
Epoch=1, lr=0.0001
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](1/11): Loss: 0.3564650416
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](2/11): Loss: 0.3581047058
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](3/11): Loss: 0.4281277061
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](4/11): Loss: 0.4021123350
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](5/11): Loss: 0.3430156112
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](6/11): Loss: 0.3826246858
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](7/11): Loss: 0.4218471050
debug=====0
debug=====1
debug=====2
debug====3
Traceback (most recent call last):
  File "train_psnr_indication.py", line 344, in <module>
    main()
  File "train_psnr_indication.py", line 164, in main
    validate(model, optimizer, epoch)
  File "train_psnr_indication.py", line 317, in validate
    for iteration, batch in enumerate(validate_data_loader, 1):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pxk/CBREN/dataset.py", line 225, in __getitem__
    frames_lr[i, :, :, :] = img  # t h w c
ValueError: could not broadcast input array from shape (536,960,3) into shape (504,960,3)
===> Epoch[1](8/11): Loss: 0.3005030155
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](9/11): Loss: 0.2850322127
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](10/11): Loss: 0.3839508891
debug=====0
debug=====1
debug=====2
debug====3
===> Epoch[1](11/11): Loss: 0.3315883279
|||||||||||||||||||||min_epoch_loss is 0.3630337851|||||||||||||||||||||
----Start Validate----