Namespace(batchSize=16, cuda=True, dataset='datasets/', lr=0.0001, momentum=0.9, nEpochs=3000, resume='', start_epoch=1, step=1000, test_path='dataset/test/', threads=16, validate_path='datasets/validate/', weight_decay=0)
===> Loading datasets
===> Building model
n_pyramids: 1 n_pyramid_cells: (3, 2, 1, 1, 1, 1)
===> Setting GPU
===> Setting Optimizer
===> Training
Epoch=1, lr=0.0001
===> Epoch[1](1/11): Loss: 0.3842422962
===> Epoch[1](2/11): Loss: 0.3759435117
===> Epoch[1](3/11): Loss: 0.3691446483
===> Epoch[1](4/11): Loss: 0.3657272756
===> Epoch[1](5/11): Loss: 0.4471130073
===> Epoch[1](6/11): Loss: 0.4825868309
Traceback (most recent call last):
  File "train_psnr_indication.py", line 313, in <module>
    main()
  File "train_psnr_indication.py", line 160, in main
    validate(model, optimizer, epoch)
  File "train_psnr_indication.py", line 271, in validate
    validate_set = get_validate_set()
  File "/home/pxk/CBREN/dataset.py", line 25, in get_validate_set
    return ValidateDataset(dir=root_path)
  File "/home/pxk/CBREN/dataset.py", line 199, in __init__
    target_folder_path = '{}{}/'.format(self.target_path, _f)  # datasets/validate/gt_frame/200 || 100||
AttributeError: 'ValidateDataset' object has no attribute 'target_path'
===> Epoch[1](7/11): Loss: 0.4660354853
===> Epoch[1](8/11): Loss: 0.3454682231
===> Epoch[1](9/11): Loss: 0.3495941162
===> Epoch[1](10/11): Loss: 0.3553818166
===> Epoch[1](11/11): Loss: 0.4241851568
|||||||||||||||||||||min_epoch_loss is 0.3968565789|||||||||||||||||||||
----Start Validate----