2022-03-04 11:30:16,457 INFO    MainThread:3664111 [wandb_setup.py:_flush():75] Loading settings from /home/pxk/.config/wandb/settings
2022-03-04 11:30:16,457 INFO    MainThread:3664111 [wandb_setup.py:_flush():75] Loading settings from /home/pxk/CBREN/wandb/settings
2022-03-04 11:30:16,457 INFO    MainThread:3664111 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-04 11:30:16,457 INFO    MainThread:3664111 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'train_psnr_indication.py', 'program': 'train_psnr_indication.py'}
2022-03-04 11:30:16,457 INFO    MainThread:3664111 [wandb_init.py:_log_setup():386] Logging user logs to /home/pxk/CBREN/wandb/run-20220304_113016-pl0cqccz/logs/debug.log
2022-03-04 11:30:16,457 INFO    MainThread:3664111 [wandb_init.py:_log_setup():387] Logging internal logs to /home/pxk/CBREN/wandb/run-20220304_113016-pl0cqccz/logs/debug-internal.log
2022-03-04 11:30:16,458 INFO    MainThread:3664111 [wandb_init.py:init():420] calling init triggers
2022-03-04 11:30:16,458 INFO    MainThread:3664111 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {'lr_rate': 0.0001, 'epoch': 5000, 'batch_size': 16}
2022-03-04 11:30:16,458 INFO    MainThread:3664111 [wandb_init.py:init():471] starting backend
2022-03-04 11:30:16,458 INFO    MainThread:3664111 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-04 11:30:16,467 INFO    MainThread:3664111 [backend.py:ensure_launched():219] starting backend process...
2022-03-04 11:30:16,472 INFO    MainThread:3664111 [backend.py:ensure_launched():225] started backend process with pid: 3664418
2022-03-04 11:30:16,473 INFO    MainThread:3664111 [wandb_init.py:init():480] backend started and connected
2022-03-04 11:30:16,475 INFO    MainThread:3664111 [wandb_init.py:init():550] updated telemetry
2022-03-04 11:30:16,491 INFO    MainThread:3664111 [wandb_init.py:init():581] communicating current version
2022-03-04 11:30:17,604 INFO    MainThread:3664111 [wandb_init.py:init():586] got version response 
2022-03-04 11:30:17,604 INFO    MainThread:3664111 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-04 11:30:20,669 ERROR   Thread-1  :3664111 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8e29165850>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e29165850>: Failed to establish a new connection: [Errno 113] No route to host')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8e29165850>: Failed to establish a new connection: [Errno 113] No route to host')))
2022-03-04 11:30:36,911 WARNING MainThread:3664111 [wandb_init.py:init():972] interrupted
Traceback (most recent call last):
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 597, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 210, in communicate_run
    return self._communicate_run(run, timeout=timeout)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 311, in _communicate_run
    resp = self._communicate(req, timeout=timeout)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/home/pxk/anaconda3/envs/cxy/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
